name: flutter_miui
description: Flutter package for using MIUI11 design Widget with Simple Animations which support Dialog,Button,TextField etc.
version: 0.0.5
homepage: https://github.com/laiiihz/flutter_miui

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:


